name: Manual deploy - VerdantTechWindows (publish profile)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Publish
        run: |
          csproj=$(git ls-files '*.csproj' | head -n 1)
          echo "Publishing project: $csproj"
          dotnet publish "$csproj" -c Release -o ./publish

      - name: Deploy to Azure Web App (Publish Profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: VerdantTechWindows
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./publish
